#=================================================================
# minio (上传图片需要，需配置成自己的地址)
#=================================================================
minio:
  endpoint: http://121.37.160.132:9000
  accessKey: quanxiaoha
  secretKey: quanxiaoha